
# fb magic bot
#ACCESS_TOKEN = 'EAAESHHaUabIBADcrZAhdigkIPkjZBNZAIrDEunBGC69Jpwv7trAjZBewYum0zl2X1GjTeRMAGsciA6oj9SKZAI3yvDj4rtaVxfcmZBgdXbwAvicHepeLfq9FWfznUZC3sSgIwnXLheaxu3zKEdxJePPDy75e4Vj6x76HZAzX8bcYqZCybfq7ob5L5'   #ACCESS_TOKEN = os.environ['ACCESS_TOKEN']

# fb bot
ACCESS_TOKEN = 'EAAKrLyeQf6oBAEsp3gBfZAk3PPxDufVnziHk4RtYK6RSfHgasKxKC8l9Aj0iTlhH0oPLxcOjQ7e9nu7E8rQZC5mZCMtpA5YVo0vcx1kwqUhvGbWcPO53EPYfsCcLL3BZCZBikuQojLGIlYuqnI9Ey5vX91oTBbJCFL3rRuSW2KPZC46I7eL0Q6'   #ACCESS_TOKEN = os.environ['ACCESS_TOKEN']

VERIFY_TOKEN = 'JAHIDTOEKN@'   #VERIFY_TOKEN = os.environ['VERIFY_TOKEN']
